print("*******************Main Menu*****************")
print("1. Read CSV file of grades")
print("2. Generate student report file")
print("3. Generate student report charts")
print("4. Generate class report file")
print("5. Generate class report charts")
print("6. Quit")
print("************************************************")

option = input("")